[package]
name = "pusoy_dos"
version = "0.1.0"
authors = ["Ben Brunton <benbrunton@hotmail.com>"]

[dependencies]
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
#rustc-serialize = "0.3"
